prooph_event_store:
    stores:
        default:
            event_store: App\SharedKernel\Infra\Persistence\FileSystemEventStore
            repositories:
                product:
                    repository_class: App\Catalog\Infra\ProophProductRepository
                    aggregate_type: App\Catalog\Domain\Product
                    aggregate_translator: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator
                    one_stream_per_aggregate: true
                listing:
                    repository_class: App\Listing\Infra\ProophProductListRepository
                    aggregate_type: App\Listing\Domain\ProductList
                    aggregate_translator: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator
                    one_stream_per_aggregate: true
                basket:
                    repository_class: App\Basket\Infra\ProophBasketRepository
                    aggregate_type: App\Basket\Domain\Basket
                    aggregate_translator: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator
                    one_stream_per_aggregate: true
                contribution:
                    repository_class: App\Contribution\Infra\ProophContributionRepository
                    aggregate_type: App\Contribution\Domain\Contribution
                    aggregate_translator: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator
                    one_stream_per_aggregate: true

services:
    _defaults:
        public: false

    Prooph\EventStore\EventStore: '@prooph_event_store.default'

    Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator: ~

    Prooph\EventSourcing\Aggregate\AggregateType: ~

    Prooph\Common\Messaging\FQCNMessageFactory: ~

    Prooph\Common\Messaging\NoOpMessageConverter: ~
