product_index:
   path: /
   methods: [GET]
   controller: App\Catalog\Ui\Controller\ProductController::index

basket_index:
   path: /cart
   methods: [GET]
   controller: App\Basket\Ui\Controller\BasketController::index

basket_cancel:
   path: /cart/cancel
   methods: [GET]
   controller: App\Basket\Ui\Controller\BasketController::cancel

basket_add:
   path: /cart
   methods: [POST]
   controller: App\Basket\Ui\Controller\BasketController::addProduct

thanks:
   path: /thanks
   methods: [GET]
   controller: App\Basket\Ui\Controller\BasketController::thanks

contribution_checkout:
   path: /checkout
   methods: [GET, POST]
   controller: App\Contribution\Ui\Controller\ContributionController::checkout

contribution_confirm:
   path: /confirm/{contributionId}
   controller: App\Contribution\Ui\Controller\ContributionController::confirm

waiting:
   path: /waiting.html
   controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
   defaults:
      template: waiting.html.twig
   methods: GET

bo:
   resource: routes_admin.yaml
   name_prefix: admin_
   prefix: /bo
