listing_index:
    path: /listing
    controller: App\Listing\Ui\Controller\AdminController::index

listing_new:
    path: /listing/new
    controller: App\Listing\Ui\Controller\AdminController::new

listing_show:
    path: /listing/{listId}
    controller: App\Listing\Ui\Controller\AdminController::show

product_new:
    path: /listing/{listId}/new
    controller: App\Catalog\Ui\Controller\AdminController::new

product_edit:
    path: /listing/{listId}/product/{productId}/edit
    controller: App\Catalog\Ui\Controller\AdminController::edit

listing_enable:
    path: /listing/{listId}/enable
    controller: App\Listing\Ui\Controller\AdminController::enable

listing_disable:
    path: /listing/{listId}/disable
    controller: App\Listing\Ui\Controller\AdminController::disable

listing_sort:
    path: /listing/{listId}/sort
    controller: App\Listing\Ui\Controller\AdminController::sortProducts

listing_dashboard:
    path: /listing/{listId}/dashboard
    controller: App\Listing\Ui\Controller\AdminController::dashboard

contribution_index:
    path: /listing/{listId}/contribution
    controller: App\Contribution\Ui\Controller\AdminController::index

contribution_confirm:
    path: /listing/{listId}/contribution/{contributionId}/confirm
    controller: App\Contribution\Ui\Controller\AdminController::confirm

login:
    path:       /login
    controller: App\SharedKernel\Bridge\AdminSecurityController::login
    methods: GET|POST

logout:
    path: /logout
    methods: GET
