parameters:
    eventstore.root_dir: '%kernel.project_dir%/var/data/event-store'
    projection.root_dir: '%kernel.project_dir%/var/data/projections'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
