# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(CURRENT_LIST): ''
    env(LYDIA_PHONE): '0711223344'
    env(LYDIA_DEBUG): true
    env(AWS_ACCESS_KEY_ID): ''
    env(AWS_SECRET_ACCESS_KEY): ''
    eventstore.root_dir: 's3://event-store-pourlili'
    projection.root_dir: 's3://projection-pourlili'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $eventBus: '@event.bus'
            $currentList: '%env(string:CURRENT_LIST)%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,*/Infra/Prooph*}'

    App\SharedKernel\Infra\Persistence\FileSystemEventStore:
        arguments:
            - '%eventstore.root_dir%'
            - '@Prooph\Common\Messaging\FQCNMessageFactory'
            - '@Prooph\Common\Messaging\NoOpMessageConverter'

    App\Catalog\Domain\ProductRepository:
        alias: 'product'

    App\Listing\Domain\ProductListRepository:
        alias: 'listing'

    App\Basket\Domain\BasketRepository:
        alias: 'basket'

    App\Contribution\Domain\ContributionRepository:
        alias: 'contribution'

    App\SharedKernel\Bridge\MessengerProophBridge:
        tags:
            - { name: 'prooph_event_store.plugin' }

    App\SharedKernel\Projection\Projector:
        arguments:
            - '%projection.root_dir%'

    App\SharedKernel\Bridge\QueryBus:
        autowire: false
        autoconfigure: false
        arguments:
            - '@query.bus'

    App\SharedKernel\Bridge\CommandBus:
        autowire: false
        autoconfigure: false
        arguments:
            - '@command.bus'

    # We want to retrict bus usage to dedicated query/command
    query_handlers.catalog:
        namespace: App\Catalog\App\Query\
        resource: '%kernel.project_dir%/src/Catalog/App/Query/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: query.bus }

    command_handlers.catalog:
        namespace: App\Catalog\App\Command\
        resource: '%kernel.project_dir%/src/Catalog/App/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    query_handlers.basket:
        namespace: App\Basket\App\Query\
        resource: '%kernel.project_dir%/src/Basket/App/Query/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: query.bus }

    command_handlers.basket:
        namespace: App\Basket\App\Command\
        resource: '%kernel.project_dir%/src/Basket/App/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    command_handlers.contribution:
        namespace: App\Contribution\App\Command\
        resource: '%kernel.project_dir%/src/Contribution/App/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    query_handlers.contribution:
        namespace: App\Contribution\App\Query\
        resource: '%kernel.project_dir%/src/Contribution/App/Query/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: query.bus }

    query_handlers.listing:
        namespace: App\Listing\App\Query\
        resource: '%kernel.project_dir%/src/Listing/App/Query/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: query.bus }

    command_handlers.listing:
        namespace: App\Listing\App\Command\
        resource: '%kernel.project_dir%/src/Listing/App/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    controller.catalog:
        namespace: App\Catalog\Ui\Controller\
        resource: '%kernel.project_dir%/src/Catalog/Ui/Controller/*'
        public: true
        tags:
            - 'controller.service_arguments'

    controller.basket:
        namespace: App\Basket\Ui\Controller\
        resource: '%kernel.project_dir%/src/Basket/Ui/Controller/*'
        public: true
        tags:
            - 'controller.service_arguments'

    controller.contribution:
        namespace: App\Contribution\Ui\Controller\
        resource: '%kernel.project_dir%/src/Contribution/Ui/Controller/*'
        public: true
        tags:
            - 'controller.service_arguments'

    controller.listing:
        namespace: App\Listing\Ui\Controller\
        resource: '%kernel.project_dir%/src/Listing/Ui/Controller/*'
        public: true
        tags:
            - 'controller.service_arguments'

    App\Contribution\Infra\Network\HttpLydiaPaymentGateway:
        arguments:
            $phone: '%env(string:LYDIA_PHONE)%'
            $debug: '%env(bool:LYDIA_DEBUG)%'

    Aws\S3\S3Client:
        arguments:
            -
                version: latest
                region: eu-west-3
                credentials:
                    key: '%env(AWS_ACCESS_KEY_ID)%'
                    secret: '%env(AWS_SECRET_ACCESS_KEY)%'
