name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: composer
      run: composer install --dev
    - name: behat
      run: vendor/bin/behat --strict --colors
